# Generated by Django 5.0.1 on 2024-06-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='cuda_device',
            field=models.IntegerField(default=0),
        ),
    ]
