# Generated by Django 5.0.1 on 2024-07-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_imageproc_cuda_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='detections',
            name='detection_frame_with_box',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
    ]
