# Generated by Django 5.0.1 on 2024-08-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_detections_detection_frame_with_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='detections',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
