# Generated by Django 5.0.1 on 2024-08-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_detectionperson_marked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionperson',
            old_name='marked',
            new_name='marked_person',
        ),
    ]
