# Generated by Django 5.0.1 on 2024-08-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_marked_detectionperson_marked_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveDetectionResult',
        ),
    ]
