# Generated by Django 5.0.1 on 2024-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_delete_savedetectionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='camera_type',
            field=models.CharField(blank=True, choices=[('queue', 'queue'), ('setting', 'setting'), ('gate', 'gate'), (None, None)], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageproc',
            name='type',
            field=models.CharField(choices=[('face', 'face'), ('counting', 'counting')], default='face', max_length=255),
        ),
    ]
