# Generated by Django 5.0.1 on 2024-09-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_imageproc_camera_type_alter_imageproc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproc',
            old_name='type',
            new_name='stream_type',
        ),
    ]
