# Generated by Django 5.0.1 on 2024-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_rename_type_imageproc_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='camera_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
