# Generated by Django 5.0.1 on 2024-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_imageproc_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproc',
            name='camera_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
