# Generated by Django 5.0.1 on 2024-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_imageproc_camera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='cords_type',
            field=models.CharField(choices=[('line', 'line'), ('region', 'region')], default='line', max_length=255, null=True),
        ),
    ]
