# Generated by Django 5.0.1 on 2024-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_imageproc_cords_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='taskId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
