# Generated by Django 5.0.1 on 2024-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_imageproc_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproc',
            name='taskId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
