# Generated by Django 5.0.1 on 2024-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_detections_api_detecti_created_f8a889_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
