# Generated by Django 5.0.1 on 2024-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_imageproc_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionperson',
            name='conf_value',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='detectionperson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='detections',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='detectionperson',
            index_together={('detection', 'conf_value', 'created'), ('person', 'conf_value', 'created')},
        ),
        migrations.AlterIndexTogether(
            name='detections',
            index_together={('video_source', 'created')},
        ),
        migrations.AddIndex(
            model_name='detectionperson',
            index=models.Index(fields=['person', 'conf_value', 'created'], name='Api_detecti_person__b02d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionperson',
            index=models.Index(fields=['detection', 'conf_value'], name='Api_detecti_detecti_556247_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionperson',
            index=models.Index(fields=['detection', 'person'], name='Api_detecti_detecti_4cec3a_idx'),
        ),
        migrations.AddIndex(
            model_name='detections',
            index=models.Index(fields=['video_source', 'created'], name='Api_detecti_video_s_3b0222_idx'),
        ),
    ]
