# Generated by Django 5.0.1 on 2024-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_alter_detectionperson_conf_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproc',
            name='webrtc_stream_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
