apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: facerec-app
data:
  POSTGRES_DB: FaceApi
  POSTGRES_USER: FaceApi
  PGUSER: FaceApi
  PGDATA: /var/lib/postgresql/data/pgdata
